language: java

jdk:
  - oraclejdk8
  - oraclejdk7

sudo: false

env:
  - LIB_DIR=jshellsession

script:
  - cd $LIB_DIR && mvn clean verify

notifications:
  email:
    on_success: never
    on_failure: always